"""initial schema

Revision ID: 23213b7c087e
Revises: 
Create Date: 2026-03-07 15:11:26.843465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23213b7c087e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_configs',
    sa.Column('id', sa.Uuid(), nullable=False, server_default=sa.text("gen_random_uuid()")),
    sa.Column('region', sa.String(length=10), nullable=False),
    sa.Column('fuel_type', sa.Enum('electricity', 'natural_gas', name='fuel_type_enum'), nullable=False),
    sa.Column('threshold_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('slack_webhook', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_summaries',
    sa.Column('id', sa.Uuid(), nullable=False, server_default=sa.text("gen_random_uuid()")),
    sa.Column('region', sa.String(length=10), nullable=False),
    sa.Column('fuel_type', sa.Enum('electricity', 'natural_gas', name='fuel_type_enum'), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('data_hash', sa.String(length=32), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False, server_default=sa.text("gen_random_uuid()")),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=False),
    sa.Column('fuel_type', sa.Enum('electricity', 'natural_gas', name='fuel_type_enum'), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=80), nullable=True),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('raw_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'region', 'fuel_type', 'period', name='uq_price_snapshot_source_region_fuel_period')
    )
    op.create_index('ix_price_snapshots_region_fuel_period', 'price_snapshots', ['region', 'fuel_type', 'period'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False, server_default=sa.text("gen_random_uuid()")),
    sa.Column('alert_config_id', sa.Uuid(), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=False),
    sa.Column('fuel_type', sa.Enum('electricity', 'natural_gas', name='fuel_type_enum'), nullable=False),
    sa.Column('severity', sa.Enum('warning', 'critical', name='severity_enum'), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('rolling_avg_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('deviation_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_config_id'], ['alert_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.drop_index('ix_price_snapshots_region_fuel_period', table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_table('market_summaries')
    op.drop_table('alert_configs')
    # Drop PostgreSQL enum types that were implicitly created
    sa.Enum(name='severity_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='fuel_type_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
