"""Add market_summaries table

Revision ID: dc43da2647fd
Revises: a1b2c3d4e5f6
Create Date: 2026-03-08 12:29:43.695974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc43da2647fd'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert_configs', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('alerts', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('market_summaries', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_market_summaries_data_hash'), 'market_summaries', ['data_hash'], unique=False)
    op.create_index(op.f('ix_market_summaries_region'), 'market_summaries', ['region'], unique=False)
    op.drop_column('market_summaries', 'fuel_type')
    op.drop_column('market_summaries', 'generated_at')
    op.alter_column('price_snapshots', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('price_snapshots', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.add_column('market_summaries', sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('market_summaries', sa.Column('fuel_type', postgresql.ENUM('electricity', 'natural_gas', name='fuel_type_enum'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_market_summaries_region'), table_name='market_summaries')
    op.drop_index(op.f('ix_market_summaries_data_hash'), table_name='market_summaries')
    op.alter_column('market_summaries', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('alerts', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('alert_configs', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    # ### end Alembic commands ###
